name: Common Sense in IT, from Management to Architecture
description: Notes and articles on High Load, Big Data, Java, Architecture, R&D and Management
meta_description: "Dmitry Sotnyk. Notes and articles on High Load, Big Data, Java, Architecture and Management"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://sotnikdv.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://sotnikdv.github.io'
author:         'Dmitry Sotnyk'
